# analyze performance of S&P 500 following all-time highs

# S&P 500 daily price data
# generated by clean_sp500_prices.py
sp.data <- read.csv("./prepared_data/sp500_daily_cleaned.csv", sep=",", stringsAsFactors = FALSE)
head(sp.data)
tail(sp.data)

# pull out all-time highs, 52-week highs, 52-week lows
sp.data$high.all.time <- FALSE
current.high <- 0
# sp.data$high.52.week <- FALSE
# sp.data$low.52.week <- FALSE
for (i in 1:nrow(sp.data)) {
  if (sp.data$Adj.Close[i] > current.high) {
    sp.data$high.all.time[i] <- TRUE
    current.high <- sp.data$Adj.Close[i]
  }
}

table(sp.data$high.all.time)

# sp.data <- sp.data[sp.data$Date > as.Date('2000-01-01'),]

# returns data
sp.data$price.change.180.ahead <- sp.data$Adj.Close.180.Ahead / sp.data$Adj.Close - 1
sp.data$price.change.365.ahead <- sp.data$Adj.Close.365.Ahead / sp.data$Adj.Close - 1
sp.data$price.change.90.ahead <- sp.data$Adj.Close.90.Ahead / sp.data$Adj.Close - 1
sp.data$price.change.30.ahead <- sp.data$Adj.Close.30.Ahead / sp.data$Adj.Close - 1

boxplot(sp.data$price.change.365.ahead ~ sp.data$high.all.time)
boxplot(sp.data$price.change.365.ahead ~ sp.data$high.all.time, outline = FALSE)
summary(sp.data$price.change.365.ahead[sp.data$high.all.time])
summary(sp.data$price.change.365.ahead[!sp.data$high.all.time])

boxplot(sp.data$price.change.180.ahead ~ sp.data$high.all.time)
boxplot(sp.data$price.change.180.ahead ~ sp.data$high.all.time, outline = FALSE)
summary(sp.data$price.change.180.ahead[sp.data$high.all.time])
summary(sp.data$price.change.180.ahead[!sp.data$high.all.time])

boxplot(sp.data$price.change.90.ahead ~ sp.data$high.all.time)
boxplot(sp.data$price.change.90.ahead ~ sp.data$high.all.time, outline = FALSE)
summary(sp.data$price.change.90.ahead[sp.data$high.all.time])
summary(sp.data$price.change.90.ahead[!sp.data$high.all.time])

boxplot(sp.data$price.change.30.ahead ~ sp.data$high.all.time)
boxplot(sp.data$price.change.30.ahead ~ sp.data$high.all.time, outline = FALSE)
summary(sp.data$price.change.30.ahead[sp.data$high.all.time])
summary(sp.data$price.change.30.ahead[!sp.data$high.all.time])

